Solar_Exception: [CHG] In method __toString(), when at the CLI, output the message a second time at the end, so that the message is the last line of output, not the stack trace.  This helps with CLI programs that look at the last line for messaging (i.e., most of them).